name: Generate Sphinx Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-docs:
    name: Build Sphinx Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autodoc-typehints myst-parser

      - name: Create Sphinx project
        run: |
          mkdir -p docs/source
          sphinx-quickstart --quiet --sep --project "NoKeeA" --author "Your Name" --version "0.1" --language en --ext-autodoc --ext-napoleon --ext-viewcode --no-makefile --no-batchfile --output-dir docs

      - name: Configure Sphinx
        run: |
          echo "import os, sys" >> docs/source/conf.py
          echo "sys.path.insert(0, os.path.abspath('../src'))" >> docs/source/conf.py
          echo "extensions += ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'myst_parser']" >> docs/source/conf.py

      - name: Generate API Docs
        run: |
          sphinx-apidoc -o docs/source ../src/NoKeeA

      - name: Build HTML Docs
        run: |
          make -C docs html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-documentation
          path: docs/build/html
