name: Run Tests and Enforce Coverage

on:
  push:
  pull_request:
    branches:
      - main
      - release
      - hotfix

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          apt update
          apt install -y ffmpeg tesseract-ocr
          TESSERACT_PATH=$(which tesseract)
          sed -i '/^TESSERACT_PATH=/d' /etc/environment
          echo "TESSERACT_PATH=\"$TESSERACT_PATH\"" | sudo tee -a /etc/environment > /dev/null
          export TESSERACT_PATH="$TESSERACT_PATH"
          echo "TESSERACT_PATH wurde gesetzt auf $TESSERACT_PATH"
          
          pip install poetry
          poetry install --no-root

      - name: Run Tests with Coverage
        run: |
          export STREAMLIT_UI_SCRIPT_TEST=../../src/NoKeeA/UI/streamlit_ui.py &&
          export STREAMLIT_UI_SCRIPT=src/NoKeeA/UI/streamlit_ui.py &&
          cd $GITHUB_WORKSPACE &&
          poetry run pytest --cov=src --cov-report=term-missing --cov-fail-under=70
